// Mock data for WordPress/WooCommerce development
export const mockProducts = [
  {
    id: 1,
    name: "Premium Wireless Headphones",
    slug: "premium-wireless-headphones",
    permalink: "https://example.com/product/premium-wireless-headphones/",
    date_created: "2024-01-15T10:00:00",
    date_modified: "2024-01-15T10:00:00",
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "High-quality wireless headphones with noise cancellation and premium sound quality. Perfect for music lovers and professionals.",
    short_description: "Premium wireless headphones with noise cancellation",
    sku: "PWH-001",
    price: "199.99",
    regular_price: "199.99",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_to: null,
    on_sale: false,
    purchasable: true,
    total_sales: 45,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "0.5",
    dimensions: { length: "20", width: "15", height: "8" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "4.5",
    rating_count: 12,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      { id: 1, name: "Electronics", slug: "electronics" },
      { id: 2, name: "Audio", slug: "audio" }
    ],
    tags: [
      { id: 1, name: "wireless", slug: "wireless" },
      { id: 2, name: "premium", slug: "premium" }
    ],
    images: [
      {
        id: 1,
        src: "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg",
        name: "headphones-1",
        alt: "Premium Wireless Headphones"
      }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html: "<span class=\"amount\">$199.99</span>",
    related_ids: [2, 3],
    meta_data: [],
    stock_status: "instock",
    has_options: false,
    post_password: "",
    global_unique_id: ""
  },
  {
    id: 2,
    name: "Smart Fitness Watch",
    slug: "smart-fitness-watch",
    permalink: "https://example.com/product/smart-fitness-watch/",
    date_created: "2024-01-16T10:00:00",
    date_modified: "2024-01-16T10:00:00",
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "Advanced fitness tracking watch with heart rate monitoring, GPS, and smartphone connectivity. Track your workouts and stay connected.",
    short_description: "Smart fitness watch with GPS and heart rate monitoring",
    sku: "SFW-002",
    price: "299.99",
    regular_price: "349.99",
    sale_price: "299.99",
    date_on_sale_from: null,
    date_on_sale_to: null,
    on_sale: true,
    purchasable: true,
    total_sales: 32,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "0.1",
    dimensions: { length: "5", width: "4", height: "1" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "4.8",
    rating_count: 28,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      { id: 1, name: "Electronics", slug: "electronics" },
      { id: 3, name: "Fitness", slug: "fitness" }
    ],
    tags: [
      { id: 3, name: "smart", slug: "smart" },
      { id: 4, name: "fitness", slug: "fitness" }
    ],
    images: [
      {
        id: 2,
        src: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg",
        name: "smartwatch-1",
        alt: "Smart Fitness Watch"
      }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html: "<del><span class=\"amount\">$349.99</span></del> <ins><span class=\"amount\">$299.99</span></ins>",
    related_ids: [1, 3],
    meta_data: [],
    stock_status: "instock",
    has_options: false,
    post_password: "",
    global_unique_id: ""
  },
  {
    id: 3,
    name: "Portable Bluetooth Speaker",
    slug: "portable-bluetooth-speaker",
    permalink: "https://example.com/product/portable-bluetooth-speaker/",
    date_created: "2024-01-17T10:00:00",
    date_modified: "2024-01-17T10:00:00",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "Compact and powerful Bluetooth speaker with excellent sound quality and long battery life. Perfect for outdoor activities and travel.",
    short_description: "Portable Bluetooth speaker with excellent sound quality",
    sku: "PBS-003",
    price: "79.99",
    regular_price: "79.99",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_to: null,
    on_sale: false,
    purchasable: true,
    total_sales: 67,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "0.3",
    dimensions: { length: "10", width: "8", height: "6" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "4.2",
    rating_count: 18,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      { id: 1, name: "Electronics", slug: "electronics" },
      { id: 2, name: "Audio", slug: "audio" }
    ],
    tags: [
      { id: 1, name: "wireless", slug: "wireless" },
      { id: 5, name: "portable", slug: "portable" }
    ],
    images: [
      {
        id: 3,
        src: "https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg",
        name: "speaker-1",
        alt: "Portable Bluetooth Speaker"
      }
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html: "<span class=\"amount\">$79.99</span>",
    related_ids: [1, 2],
    meta_data: [],
    stock_status: "instock",
    has_options: false,
    post_password: "",
    global_unique_id: ""
  }
];

export const mockCollections = [
  {
    id: 1,
    name: "Electronics",
    slug: "electronics",
    description: "Latest electronic gadgets and devices",
    image: {
      id: 10,
      src: "https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg",
      name: "electronics",
      alt: "Electronics Collection"
    },
    count: 15,
    path: "/products?category=electronics"
  },
  {
    id: 2,
    name: "Audio",
    slug: "audio",
    description: "High-quality audio equipment",
    image: {
      id: 11,
      src: "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg",
      name: "audio",
      alt: "Audio Collection"
    },
    count: 8,
    path: "/products?category=audio"
  },
  {
    id: 3,
    name: "Fitness",
    slug: "fitness",
    description: "Fitness and health tracking devices",
    image: {
      id: 12,
      src: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg",
      name: "fitness",
      alt: "Fitness Collection"
    },
    count: 5,
    path: "/products?category=fitness"
  }
];

export const mockCart = {
  items: [],
  totals: {
    total_items: '0',
    total_items_tax: '0',
    total_fees: '0',
    total_fees_tax: '0',
    total_discount: '0',
    total_discount_tax: '0',
    total_shipping: '0',
    total_shipping_tax: '0',
    total_price: '0',
    total_tax: '0',
    currency_code: 'USD',
    currency_symbol: '$',
  },
  item_count: 0,
  needs_payment: false,
  needs_shipping: false,
};